### ISSUE TITLE
使用感谢等功能报错

### ISSUE THREAD

**Issue by ZhangSanMo** [cheezone/ZhihuVAPI#3]
代码为
```
import ZhihuVAPI as zhihu

a=zhihu.Answer('https://www.zhihu.com/question/31343133/answer/58763430')
a.thank()
```

报错信息为：
```
C:\Users\Sanmo\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
信息：People 对象 ba69961d293019bf085e0edb82c2cb92 (<ZhihuVAPI.content.People.People object at 0x0000019991509208>)初始 化
C:\Users\Sanmo\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
信息：传入 URL 得到58763430  答案
C:\Users\Sanmo\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
日志：感谢以茄之名的答案
Traceback (most recent call last):
  File "C:\Users\Sanmo\Desktop\新建文本文档.py", line 4, in <module>
    a.thank()
  File "C:\Users\Sanmo\AppData\Local\Programs\Python\Python36\lib\site-packages\ZhihuVAPI\util\zhihu.py", line 279, in warpper
    return func(self, *args, **kwargs)
  File "C:\Users\Sanmo\AppData\Local\Programs\Python\Python36\lib\site-packages\ZhihuVAPI\content\Answer.py", line 83, in thank
    url = urls(self, 'thank')('thank')
TypeError: <lambda>() takes 0 positional arguments but 1 was given
```

类似的，使用vote，down，undown这些功能都有相关错误

**Comment by cheezone** [comment]
谢谢反馈，现在已经修改好了，问题是我的函数设置不统一，你可以用`pip install ZhihuVAPI -U`安装最新版本。
